services:
  eywa-api:
    build: .
    container_name: eywa_api
    restart: always
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    networks:
      - postgresql_default
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  postgresql_default:
    external: true
