export { authRouter }           from './auth';
export { usersRouter }          from './users';
export { portfolioRouter }      from './portfolio';
export { diagnosticRouter }     from './diagnostic';
export { coursesRouter }        from './courses';
export { organizationRouter }   from './organization';
export { simbiocreacionRouter } from './simbiocreacion';
export { default as esgRouter }      from './esg';
export { validatorRouter }      from './validator';
export { certificatesRouter }   from './certificates';
export { actorsRouter }         from './actors';
